[serve]
# The address to serve on LAN.
addresses = ["127.0.0.1"]

# The port to serve on.
port = 8000

[[proxy]]
rewrite = "/api/v1/"
# backend = "http://bors.greece.local:9000/"
backend = "http://localhost:9000/"
